using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CommaExcess.Algae.Platform
{
	[Flags]
	enum AllegroDisplayFlags
	{
		ALLEGRO_WINDOWED = 1 << 0,
		ALLEGRO_FULLSCREEN = 1 << 1,
		ALLEGRO_OPENGL = 1 << 2,
		ALLEGRO_DIRECT3D_INTERNAL = 1 << 3,
		ALLEGRO_RESIZABLE = 1 << 4,
		ALLEGRO_NOFRAME = 1 << 5,
		ALLEGRO_GENERATE_EXPOSE_EVENTS = 1 << 6,
		ALLEGRO_OPENGL_3_0 = 1 << 7,
		ALLEGRO_OPENGL_FORWARD_COMPATIBLE = 1 << 8,
		ALLEGRO_FULLSCREEN_WINDOW = 1 << 9,
		ALLEGRO_MINIMIZED = 1 << 10,
		ALLEGRO_PROGRAMMABLE_PIPELINE = 1 << 11
	}

	enum AllegroDisplayOptions : int
	{
		ALLEGRO_RED_SIZE,
		ALLEGRO_GREEN_SIZE,
		ALLEGRO_BLUE_SIZE,
		ALLEGRO_ALPHA_SIZE,
		ALLEGRO_RED_SHIFT,
		ALLEGRO_GREEN_SHIFT,
		ALLEGRO_BLUE_SHIFT,
		ALLEGRO_ALPHA_SHIFT,
		ALLEGRO_ACC_RED_SIZE,
		ALLEGRO_ACC_GREEN_SIZE,
		ALLEGRO_ACC_BLUE_SIZE,
		ALLEGRO_ACC_ALPHA_SIZE,
		ALLEGRO_STEREO,
		ALLEGRO_AUX_BUFFERS,
		ALLEGRO_COLOR_SIZE,
		ALLEGRO_DEPTH_SIZE,
		ALLEGRO_STENCIL_SIZE,
		ALLEGRO_SAMPLE_BUFFERS,
		ALLEGRO_SAMPLES,
		ALLEGRO_RENDER_METHOD,
		ALLEGRO_FLOAT_COLOR,
		ALLEGRO_FLOAT_DEPTH,
		ALLEGRO_SINGLE_BUFFER,
		ALLEGRO_SWAP_METHOD,
		ALLEGRO_COMPATIBLE_DISPLAY,
		ALLEGRO_UPDATE_DISPLAY_REGION,
		ALLEGRO_VSYNC,
		ALLEGRO_DISPLAY_OPTIONS_COUNT
	}

	enum AllegroDisplayImportance
	{
		ALLEGRO_DONTCARE,
		ALLEGRO_REQUIRE,
		ALLEGRO_SUGGEST
	}
}
